name: Java CI with Gradle (MySQL)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app
          MYSQL_USER: app
          MYSQL_PASSWORD: app
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Start SUT
        run: java -jar ./artifacts/aqa-shop.jar &
        
      - name: Wait for services
        run: |
          sleep 15
          docker exec mysql mysql -uapp -papp -e "SELECT 1" app || exit 1
        
      - name: Run Tests with MySQL
        continue-on-error: true
        run: ./gradlew clean test -Ddb.url=jdbc:mysql://localhost:3306/app -Dselenide.headless=true --info
        
      - name: Generate Allure Report
        if: always()
        run: |
          ./gradlew allureReport
          mkdir -p allure-results
          cp -r build/allure-results allure-results
          
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results
          retention-days: 3
